version: '2'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $container_id
# docker-compose images
# docker-compose logs --tail 20 repo_name

services:

  postgres_db:
    image: postgres
    container_name: training_app_db
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: postgres 
      POSTGRES_USER: postgres
      POSTGRES_DB: mailwall
    ports:    # Set up ports exposed for other containers to connect to
      - 5433:5432
    networks:
      - app-tier
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  python_app:
    container_name: training_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres_db
    networks:
      - app-tier
    volumes:
      - ./static:/app/static
    command:
      tail -f /dev/null


networks:
  app-tier:
    driver: bridge
