"""empty message

Revision ID: 516439b76a8f
Revises: 7cf492dc6300
Create Date: 2022-03-18 15:56:25.324082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516439b76a8f'
down_revision = '7cf492dc6300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
